// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6.Models;

namespace mission6.Migrations
{
    [DbContext(typeof(MovieEntryContext))]
    [Migration("20230215214436_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Documentary"
                        });
                });

            modelBuilder.Entity("mission6.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "JK Rowling",
                            Edited = false,
                            LentTo = "No one",
                            Notes = "This was a great film",
                            Rating = "PG",
                            Title = "Harry Potter",
                            Year = 2007
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            Director = "JK Rowling",
                            Edited = false,
                            LentTo = "No one",
                            Notes = "This was a great film as well",
                            Rating = "PG-13",
                            Title = "Harry Potter: The Chamber of Secrets",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            Director = "JK Rowling",
                            Edited = false,
                            LentTo = "No one",
                            Notes = "This was a great film too!",
                            Rating = "PG-13",
                            Title = "Harry Potter: The Prisoner of Azkaban",
                            Year = 2012
                        });
                });

            modelBuilder.Entity("mission6.Models.MovieResponse", b =>
                {
                    b.HasOne("mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
